title: lazy-paging-kmp
description: A Kotlin Multiplatform Compose library for stateful, paged lazy columns backed by AndroidX Paging.
baseurl: "/lazy-paging-kmp"
url: ""

remote_theme: just-the-docs/just-the-docs

color_scheme: dark

aux_links:
  "GitHub":
    - "https://github.com/felipearpa/lazy-paging-kmp"

nav_sort: order

heading_anchors: true

permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
